---
abstract: "class to access the function of translation provided by \"Bing Translation Api\". "
author:
  - 'Milovidov Mikhail <milovidovwork@yandex.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Translate-Bing
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Test::More: 0
  URI::Escape: 0
  XML::Simple: 0
version: 0.02
